[versions]

# Android
androidGradlePlugin = "8.7.1"

# Kotlin
kotlin = "2.1.0"
coroutines = "1.10.1"
serialization = "1.7.3"
ksp = "2.1.0-1.0.29"

# Dagger
dagger = "2.54"
androidxhilt = "1.2.0"

# AndroidX
androidx-activity = "1.10.0-rc01"
androidx-appcompat = "1.7.0"
androidx-benchmark = "1.3.3"
androidx-browser = "1.8.0"
androidx-core = "1.15.0"
androidx-datastore = "1.1.1"
androidx-lifecycle = "2.9.0-alpha08"
androidx-navigation = "2.9.0-alpha04"
androidx-profileinstaller = "1.4.1"
androidx-room = "2.7.0-alpha12"
androidx-startup = "1.2.0"
androidx-window = "1.4.0-alpha05"
androidx-work = "2.10.0"

# Compose
compose-bom = "2024.12.01"
readmore = "1.5.6"
materialmotion = "1.1.3"
photo-compose = "1.0.1"

# Etc
coil = "3.0.4"
dependencyGuard = "0.5.0"
retrofit = "2.11.0"
timber = "5.0.1"


[libraries]

# Android
android-desugar-jdk = "com.android.tools:desugar_jdk_libs:2.1.4"

# Kotlin

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

# Dagger

dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }
dagger-hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger" }

androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androidxhilt" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidxhilt" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxhilt" }

# AndroidX

androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-benchmark-macro-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "androidx-benchmark" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core"}
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }

androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "androidx-lifecycle" }
androidx-lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle" }

androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }

androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "androidx-profileinstaller" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }

androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidx-startup" }
androidx-window = { module = "androidx.window:window", version.ref = "androidx-window" }

androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "androidx-work" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "androidx-work" }

# Compose

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material = { module = "androidx.compose.material:material" }
compose-materialIconsExtended = { module = "androidx.compose.material:material-icons-extended" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-animation-graphics = { module = "androidx.compose.animation:animation-graphics" }

readmore-material = { module = "com.webtoonscorp.android:readmore-material", version.ref = "readmore" }

photo-compose = { module = "io.github.fornewid:photo-compose", version.ref = "photo-compose" }

materialmotion-compose-core = { module = "io.github.fornewid:material-motion-compose-core", version.ref = "materialmotion" }

# Test
test-junit =  "junit:junit:4.13.2"

androidx-test-core = "androidx.test:core-ktx:1.5.0"
androidx-test-rules = "androidx.test:rules:1.5.0"
androidx-test-runner = "androidx.test:runner:1.5.2"
androidx-test-ext-junit = "androidx.test.ext:junit-ktx:1.1.5"
androidx-test-espresso = "androidx.test.espresso:espresso-core:3.5.1"
androidx-test-uiautomator = "androidx.test.uiautomator:uiautomator:2.3.0"

# Etc

coil-runtime = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }


# Dependencies of the included build-logic
android-pluginGradle = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
kotlin-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
compose-compiler-pluginGradle = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }


[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
dependencyGuard = { id = "com.dropbox.dependency-guard", version.ref = "dependencyGuard" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "androidx-benchmark" }
