[versions]

# Android
androidGradlePlugin = "8.4.1"

# Kotlin
kotlin = "2.0.0"
coroutines = "1.8.1"
serialization = "1.6.3"
ksp = "2.0.0-1.0.21"

# Dagger
dagger = "2.51.1"
androidxhilt = "1.2.0"

# AndroidX
androidx-activity = "1.9.0"
androidx-appcompat = "1.7.0"
androidx-benchmark = "1.2.4"
androidx-browser = "1.8.0"
androidx-constraintlayout = "2.1.4"
androidx-core = "1.13.1"
androidx-datastore = "1.1.1"
androidx-fragment = "1.7.1"
androidx-lifecycle = "2.8.1"
androidx-navigation = "2.7.7"
androidx-profileinstaller = "1.3.1"
androidx-room = "2.6.1"
androidx-startup = "1.1.1"
androidx-window = "1.3.0"
androidx-work = "2.9.0"

# Google
gms = "4.4.1"
play-appupdate = "2.1.0"
admob = "21.3.0"
firebase-bom = "33.0.0"
firebase-crashlytics = "2.9.9"
firebase-perf = "1.4.2"

# Compose
compose-bom = "2024.05.00"
accompanist = "0.34.0"
navermap-compose = "1.5.7"
readmore = "1.5.6"
materialmotion = "1.1.3"
photo-compose = "1.0.1"

# Etc
coil = "2.6.0"
dependencyGuard = "0.5.0"
retrofit = "2.11.0"
timber = "5.0.1"
kakao = "2.20.1"


[libraries]

# Android
android-desugar-jdk = "com.android.tools:desugar_jdk_libs:1.1.5"

# Kotlin

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

# Dagger

dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }
dagger-hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger" }

androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androidxhilt" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidxhilt" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxhilt" }

# AndroidX

androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-benchmark-macro-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "androidx-benchmark" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core"}
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }

androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle" }

androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }

androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "androidx-profileinstaller" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }

androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidx-startup" }
androidx-window = { module = "androidx.window:window", version.ref = "androidx-window" }

androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "androidx-work" }

# Compose

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material = { module = "androidx.compose.material:material" }
compose-materialIconsExtended = { module = "androidx.compose.material:material-icons-extended" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-animation-graphics = { module = "androidx.compose.animation:animation-graphics" }

accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }
accompanist-pagerIndicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }

readmore-material = { module = "com.webtoonscorp.android:readmore-material", version.ref = "readmore" }

photo-compose = { module = "io.github.fornewid:photo-compose", version.ref = "photo-compose" }

materialmotion-compose-core = { module = "io.github.fornewid:material-motion-compose-core", version.ref = "materialmotion" }

navermap-compose = { module = "io.github.fornewid:naver-map-compose", version.ref = "navermap-compose" }

# Test
test-junit =  "junit:junit:4.13.2"

androidx-test-core = "androidx.test:core-ktx:1.5.0"
androidx-test-rules = "androidx.test:rules:1.5.0"
androidx-test-runner = "androidx.test:runner:1.5.2"
androidx-test-ext-junit = "androidx.test.ext:junit-ktx:1.1.5"
androidx-test-espresso = "androidx.test.espresso:espresso-core:3.5.1"
androidx-test-uiautomator = "androidx.test.uiautomator:uiautomator:2.3.0"

# Google

google-play-appupdate = { module = "com.google.android.play:app-update-ktx", version.ref = "play-appupdate" }
google-admob = { module = "com.google.android.gms:play-services-ads", version.ref = "admob" }

# https://firebase.google.com/support/release-notes/android#latest_sdk_versions
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-cloudmessaging = { module = "com.google.firebase:firebase-messaging" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-dynamiclinks = { module = "com.google.firebase:firebase-dynamic-links" }
firebase-performance = { module = "com.google.firebase:firebase-perf" }
firebase-remoteconfig = { module = "com.google.firebase:firebase-config" }

# Etc

coil-runtime = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }

kakao-share = { module = "com.kakao.sdk:v2-share", version.ref = "kakao" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }


# Dependencies of the included build-logic
android-pluginGradle = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
kotlin-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
compose-compiler-pluginGradle = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }


[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
gms = { id = "com.google.gms.google-services", version.ref = "gms" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
dependencyGuard = { id = "com.dropbox.dependency-guard", version.ref = "dependencyGuard" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }
firebase-performance = { id = "com.google.firebase.firebase-perf", version.ref = "firebase-perf" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "androidx-benchmark" }
