[versions]

# Kotlin
kotlin = "1.7.20"
coroutines = "1.6.4"
serialization = "1.4.1"
ksp = "1.7.20-1.0.8"

# Dagger
dagger = "2.44.2"
androidxhilt = "1.0.0"

# AndroidX
activity = "1.6.1"
lifecycle = "2.5.1"
navigation = "2.6.0-alpha04"
room = "2.4.3"
work = "2.7.1"

# Compose
compose = "1.3.1"
composeCompiler = "1.3.2"
accompanist = "0.28.0"
metronome = "0.5.2"
navermapcompose = "1.3.0"
readmore = "1.3.1"
materialmotion = "0.10.3"

# Etc
coil = "2.2.2"
dependencyGuard = "0.3.2"
spotless = "6.11.0"
ktlint = "0.41.0"


[libraries]

android-pluginGradle = "com.android.tools.build:gradle:7.3.1"

# Kotlin

kotlin-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-serializationPluginGradle = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

# Dagger

dagger-hilt-pluginGradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }
dagger-hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger" }

androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androidxhilt" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidxhilt" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxhilt" }

# AndroidX

androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }

androidx-appcompat = "androidx.appcompat:appcompat:1.5.1"
androidx-browser = "androidx.browser:browser:1.4.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-core = "androidx.core:core-ktx:1.9.0"
androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.0.0"
androidx-fragment = "androidx.fragment:fragment-ktx:1.5.4"

androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }

androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
androidx-navigation-dynamicFeaturesFragment = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "navigation" }
androidx-navigation-safeArgsPluginGradle = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

androidx-startup = "androidx.startup:startup-runtime:1.1.1"
androidx-window = "androidx.window:window:1.1.0-alpha04"

androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "work" }

androidx-benchmark-macro-junit4 = "androidx.benchmark:benchmark-macro-junit4:1.1.1"
androidx-profileinstaller = "androidx.profileinstaller:profileinstaller:1.2.0"

# Compose

compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-materialIconsExtended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-runtimeLivedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-animation-graphics = { module = "androidx.compose.animation:animation-graphics", version.ref = "compose" }

accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pagerIndicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }

metronome-material = { module = "com.github.fornewid.metronome:material", version.ref = "metronome" }
metronome-visibility = { module = "com.github.fornewid.metronome:visibility", version.ref = "metronome" }
metronome-zoomable = { module = "com.github.fornewid.metronome:zoomable", version.ref = "metronome" }

readmore-material = { module = "com.webtoonscorp.android:readmore-material", version.ref = "readmore" }

materialMotionCompose-core = { module = "io.github.fornewid:material-motion-compose-core", version.ref = "materialmotion" }
materialMotionCompose-navigation = { module = "io.github.fornewid:material-motion-compose-navigation", version.ref = "materialmotion" }

# Test
test-junit =  "junit:junit:4.13"

androidx-test-core = "androidx.test:core-ktx:1.5.0"
androidx-test-rules = "androidx.test:rules:1.5.0"
androidx-test-runner = "androidx.test:runner:1.5.0"
androidx-test-ext-truth = "androidx.test.ext:truth:1.5.0"
androidx-test-ext-junit = "androidx.test.ext:junit-ktx:1.1.4"
androidx-test-espresso = "androidx.test.espresso:espresso-core:3.5.0"
androidx-test-uiautomator = "androidx.test.uiautomator:uiautomator:2.2.0"

# Google

google-pluginGradle = "com.google.gms:google-services:4.3.14"
google-play-featureDelivery = "com.google.android.play:feature-delivery-ktx:2.0.1"
google-play-appUpdate = "com.google.android.play:app-update-ktx:2.0.1"
google-ads = "com.google.android.gms:play-services-ads:21.3.0"

firebase-bom = { module = "com.google.firebase:firebase-bom", version = "31.1.0" }
firebase-crashlytics-pluginGradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version = "2.9.2" }
firebase-perf-pluginGradle = { module = "com.google.firebase:perf-plugin", version = "1.4.2" }

# Etc

coil-runtime = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

retrofit-runtime = "com.squareup.retrofit2:retrofit:2.9.0"
retrofit-serialization = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:0.8.0"
lottie-compose = "com.airbnb.android:lottie-compose:5.2.0"
kakaoLink = "com.kakao.sdk:v2-share:2.11.2"
naverMapCompose = { module = "io.github.fornewid:naver-map-compose", version.ref = "navermapcompose" }
playServicesLocation = "com.google.android.gms:play-services-location:17.1.0"
timber = "com.jakewharton.timber:timber:5.0.1"
threetenAbp = "com.jakewharton.threetenabp:threetenabp:1.4.3"

dependencyGuard-pluginGradle = { module = "com.dropbox.dependency-guard:dependency-guard", version.ref = "dependencyGuard" }
spotless-pluginGradle = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
dependencyGuard = { id = "com.dropbox.dependency-guard", version.ref = "dependencyGuard" }
