[versions]

# Android
androidGradlePlugin = "8.1.4"
gms = "4.3.14"

# Kotlin
kotlin = "1.9.10"
coroutines = "1.7.3"
serialization = "1.5.0"
ksp = "1.9.10-1.0.13"

# Dagger
dagger = "2.45"
androidxhilt = "1.0.0"

# AndroidX
activity = "1.6.1"
lifecycle = "2.6.1"
navigation = "2.6.0-alpha08"
room = "2.4.3"
work = "2.8.1"

# Compose
compose-bom = "2023.05.01"
composeCompiler = "1.5.3"
accompanist = "0.30.0"
metronome = "0.5.2"
navermapcompose = "1.3.3"
readmore = "1.4.0"
materialmotion = "1.0.0"
photo = "1.0.0"

# Etc
coil = "2.2.2"
dependencyGuard = "0.3.2"
retrofit = "2.9.0"
retrofit-serialization = "1.0.0"


[libraries]

# Android
android-desugar-jdk = "com.android.tools:desugar_jdk_libs:1.1.5"

# Kotlin

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

# Dagger

dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }
dagger-hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger" }

androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androidxhilt" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidxhilt" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxhilt" }

# AndroidX

androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }

androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"
androidx-browser = "androidx.browser:browser:1.5.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-core = "androidx.core:core-ktx:1.10.0-rc01"
androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.0.0"
androidx-fragment = "androidx.fragment:fragment-ktx:1.5.6"

androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }

androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

androidx-startup = "androidx.startup:startup-runtime:1.1.1"
androidx-window = "androidx.window:window:1.1.0-beta01"

androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "work" }

androidx-benchmark-macro-junit4 = "androidx.benchmark:benchmark-macro-junit4:1.1.1"
androidx-profileinstaller = "androidx.profileinstaller:profileinstaller:1.3.0"

# Compose

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material = { module = "androidx.compose.material:material" }
compose-materialIconsExtended = { module = "androidx.compose.material:material-icons-extended" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-animation-graphics = { module = "androidx.compose.animation:animation-graphics" }

accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pagerIndicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }

metronome-visibility = { module = "com.github.fornewid.metronome:visibility", version.ref = "metronome" }

readmore-material = { module = "com.webtoonscorp.android:readmore-material", version.ref = "readmore" }

photo = { module = "io.github.fornewid:photo-compose", version.ref = "photo" }

materialMotionCompose-core = { module = "io.github.fornewid:material-motion-compose-core", version.ref = "materialmotion" }
materialMotionCompose-navigation = { module = "io.github.fornewid:material-motion-compose-navigation", version.ref = "materialmotion" }

# Test
test-junit =  "junit:junit:4.13"

androidx-test-core = "androidx.test:core-ktx:1.5.0"
androidx-test-rules = "androidx.test:rules:1.5.0"
androidx-test-runner = "androidx.test:runner:1.5.0"
androidx-test-ext-truth = "androidx.test.ext:truth:1.5.0"
androidx-test-ext-junit = "androidx.test.ext:junit-ktx:1.1.4"
androidx-test-espresso = "androidx.test.espresso:espresso-core:3.5.0"
androidx-test-uiautomator = "androidx.test.uiautomator:uiautomator:2.2.0"

# Google

google-play-appUpdate = "com.google.android.play:app-update-ktx:2.0.1"
google-ads = "com.google.android.gms:play-services-ads:21.3.0"

firebase-bom = { module = "com.google.firebase:firebase-bom", version = "31.2.0" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-config = { module = "com.google.firebase:firebase-config-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-dynamicLinks = { module = "com.google.firebase:firebase-dynamic-links-ktx" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging-ktx" }
firebase-perf = { module = "com.google.firebase:firebase-perf-ktx" }

# Etc

coil-runtime = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

retrofit-runtime = { module = "com.squareup.retrofit2:retrofit" , version.ref = "retrofit"}
retrofit-serialization = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter" , version.ref = "retrofit-serialization"}
kakaoLink = "com.kakao.sdk:v2-share:2.13.0"
naverMapCompose = { module = "io.github.fornewid:naver-map-compose", version.ref = "navermapcompose" }
timber = "com.jakewharton.timber:timber:5.0.1"

# Dependencies of the included build-logic
android-pluginGradle = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
kotlin-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
gms = { id = "com.google.gms.google-services", version.ref = "gms" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
dependencyGuard = { id = "com.dropbox.dependency-guard", version.ref = "dependencyGuard" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version = "2.9.2" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version = "1.4.2" }
