[versions]

# Kotlin
kotlin = "1.6.21"
coroutines = "1.6.0"

# Dagger
dagger = "2.41"
androidxhilt = "1.0.0"

# AndroidX
activity = "1.4.0"
lifecycle = "2.4.1"
navigation = "2.4.1"
room = "2.4.1"
work = "2.7.1"

# Compose
compose = "1.2.0-rc01"
accompanist = "0.24.11-rc"
metronome = "0.4.3"

# Etc
coil = "2.1.0"
dependencyGuard = "0.3.0"


[libraries]

android-pluginGradle = "com.android.tools.build:gradle:7.2.1"

# Kotlin

kotlin-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-serializationPluginGradle = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlin-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.2"

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

# Dagger

dagger-hilt-pluginGradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }
dagger-hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger" }

androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androidxhilt" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidxhilt" }

# AndroidX

androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }

androidx-appcompat = "androidx.appcompat:appcompat:1.4.1"
androidx-browser = "androidx.browser:browser:1.4.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-core = "androidx.core:core-ktx:1.8.0"
androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.0.0"
androidx-drawerlayout = "androidx.drawerlayout:drawerlayout:1.1.1"
androidx-fragment = "androidx.fragment:fragment-ktx:1.4.1"

androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }

androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
androidx-navigation-dynamicFeaturesFragment = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "navigation" }
androidx-navigation-safeArgsPluginGradle = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

androidx-recyclerview = "androidx.recyclerview:recyclerview:1.2.1"

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

androidx-startup = "androidx.startup:startup-runtime:1.1.1"
androidx-transition = "androidx.transition:transition:1.4.1"
androidx-viewpager2 = "androidx.viewpager2:viewpager2:1.1.0-beta01"

androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "work" }

androidx-benchmark-macro-junit4 = "androidx.benchmark:benchmark-macro-junit4:1.1.0"
androidx-profileinstaller = "androidx.profileinstaller:profileinstaller:1.2.0-rc01"

# Compose

compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-materialIconsExtended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-runtimeLivedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }

accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanist" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pagerIndicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }

metronome-material = { module = "com.github.fornewid.metronome:material", version.ref = "metronome" }
metronome-visibility = { module = "com.github.fornewid.metronome:visibility", version.ref = "metronome" }

# Test
test-junit =  "junit:junit:4.13"

androidx-test-core = "androidx.test:core-ktx:1.4.0"
androidx-test-runner = "androidx.test:runner:1.4.0"
androidx-test-ext-truth = "androidx.test.ext:truth:1.4.0"
androidx-test-ext-junit = "androidx.test.ext:junit-ktx:1.1.3"
androidx-test-espresso = "androidx.test.espresso:espresso-core:3.4.0"
androidx-test-uiautomator = "androidx.test.uiautomator:uiautomator:2.2.0"

# Google

google-pluginGradle = "com.google.gms:google-services:4.3.10"
google-play = "com.google.android.play:core:1.10.2"
google-ads = "com.google.android.gms:play-services-ads:20.5.0"

material-material = "com.google.android.material:material:1.5.0"
material-composeThemeAdapter = "com.google.android.material:compose-theme-adapter:1.1.11"

firebase-bom = "com.google.firebase:firebase-bom:29.0.0"
firebase-crashlytics-pluginGradle = "com.google.firebase:firebase-crashlytics-gradle:2.8.0"
firebase-perf-pluginGradle = "com.google.firebase:perf-plugin:1.4.1"

# Etc

coil-runtime = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

retrofit-runtime = "com.squareup.retrofit2:retrofit:2.9.0"
retrofit-serialization = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:0.8.0"
lottie-compose = "com.airbnb.android:lottie-compose:4.2.1"
insetter = "dev.chrisbanes.insetter:insetter:0.6.1"
photoview = "com.github.chrisbanes:PhotoView:2.3.0"
recyclerViewAnimators = "jp.wasabeef:recyclerview-animators:4.0.2"
kakaoLink = "com.kakao.sdk:v2-link:2.8.3"
naverMap = "com.naver.maps:map-sdk:3.15.0"
naverMapCompose = "io.github.fornewid:naver-map-compose:1.1.3"
playServicesLocation = "com.google.android.gms:play-services-location:17.1.0"
timber = "com.jakewharton.timber:timber:5.0.1"
threetenAbp = "com.jakewharton.threetenabp:threetenabp:1.3.1"

dependencyGuard-pluginGradle = { module = "com.dropbox.dependency-guard:dependency-guard", version.ref = "dependencyGuard" }

[plugins]
dependencyGuard = { id = "com.dropbox.dependency-guard", version.ref = "dependencyGuard" }
