plugins {
    id "moop.android.feature"
}

android {
    namespace "soup.movie.feature.notification.impl"
}

dependencies {
    implementation projects.core.logger
    implementation projects.core.resources
    implementation projects.feature.navigator.api
    implementation projects.feature.notification.api
}
