-keepnames class soup.movie.detail.DetailFragment
-keepnames class soup.movie.theatermap.TheaterMapFragment
-keepnames class soup.movie.ui.CustomProgressFragment
-keepnames class soup.movie.ui.main.MainFragment