plugins {
    id "moop.android.feature"
}

android {
    namespace 'soup.movie.feature.tasks.impl'
}

dependencies {
    implementation projects.core.kotlin
    implementation projects.core.logger
    implementation projects.core.resources
    implementation projects.core.datetime
    implementation projects.feature.tasks.api
    implementation projects.feature.notification.api

    implementation libs.androidx.hilt.work
    ksp libs.androidx.hilt.compiler

    implementation libs.androidx.work.runtime
}
