plugins {
    id "moop.android.library"
}

android {
    namespace "soup.movie.core.imageloading.impl"
}

dependencies {
    implementation projects.core.imageloading.api

    implementation libs.kotlin.stdlib

    implementation libs.androidx.startup
    implementation libs.coil.runtime
    implementation libs.coil.okhttp
}
