plugins {
    id "moop.android.library"
}

android {
    namespace "soup.movie.feature.detail"
}

dependencies {
    implementation projects.feature.navigator.api

    implementation libs.kotlin.stdlib
    implementation libs.kotlin.serialization

    implementation libs.androidx.navigation3.runtime
}
