plugins {
    id "moop.android.library"
    id "moop.android.compose"
    id "moop.android.hilt"
    id "org.jetbrains.kotlin.plugin.serialization"
}

android {
    namespace "soup.movie.feature.settings.impl"
}

dependencies {
    implementation projects.core.kotlin
    implementation projects.core.designsystem
    implementation projects.core.external
    implementation projects.core.resources
    implementation projects.data.settings.api
    implementation projects.data.model
    implementation projects.feature.settings.api

    implementation libs.kotlin.stdlib
    implementation libs.kotlin.serialization

    implementation libs.androidx.appcompat
    implementation libs.androidx.hilt.navigation.compose
    implementation libs.compose.foundation
    implementation libs.compose.material3
    implementation libs.compose.ui
    implementation libs.androidx.navigation.compose
    implementation libs.materialmotion.compose.core

    testImplementation projects.testing
    androidTestImplementation projects.testing
}
